[theme]
primaryColor = "#00FF00"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#00FF00"
font = "monospace"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false
